### ISSUE TITLE
Không hiển thị được ảnh sản phẩm ở backend??

### ISSUE THREAD

**Issue by dung111999** [ThuanNguyen386/SE04-Nhom6.2#1]

**Comment by ThuanNguyen386** [comment]
Cái này là do cái kiểu dữ liệu đầu vào của ảnh là kiểu text chứ ko phải kiểu image thì làm sao hiển thị ảnh lên được

**Comment by ThuanNguyen386** [comment]
Ae tìm được cách chữa lỗi này chưa

**Comment by duynguyen9926** [comment]
- Tôi chưa tìm được cách hiển thị ảnh được ở backend
- Nhưng hướng giải quyết của tôi là cứ upload file ảnh lên backend như bình thường (nó ở dạng dữ liệu gì cũng được, quan trọng là mình có tên của ảnh là xác định được sản phẩm rồi)
- Còn việc hiển thị ảnh thì cứ để sang bên frontend thôi

**Comment by hungpy01199** [comment]
Tôi đang tìm cách hiển thị ảnh trên backend, vẫn chưa được

**Comment by toann99** [comment]
Nên xem lại hàm controller để xử lý việc sửa ảnh và upload ảnh.

**Comment by ThuanNguyen386** [comment]
Cái này tạo ngay trên yii2 mà lại ko có kiểu định dạng ảnh nên tìm hàm controller hơi khó
T đang cố tìm cái controller đưa database vào trang web đây

**Comment by dung111999** [comment]
T sửa được bằng cách dùng thuộc tính "enctype = multipart/form-data" và thay đoạn code "<?= $form->field($model, 'image')->textInput() ?>" bằng "<?= $form->field($model, 'image')->fileInput() ?>" trong backend/views/product/_form.php
