### ISSUE TITLE
Not able to access variable in view passed from an action in controller

### ISSUE THREAD

**Issue by duynguyen9926** [ThuanNguyen386/SE04-Nhom6.2#10]
Đây là hàm bên file ProductController.php

`public function actionIndex($id) {`
          `$product = Product::findOne($id);`
`return $this->render('index',['product' => $product]);
    }`

Bên file /Views/product/index.php tôi gọi đến biến $product

`<?php echo $product ?>`

Thì nó báo "undefined variable $product"

=> làm sao để get được biến từ controller sang view

**Comment by ThuanNguyen386** [comment]
Thử xem lại cách sử dụng biến từ controller sang view trong php coi sao

**Comment by toann99** [comment]
Ô dùng thử Request.Form xem sao!

**Comment by dung111999** [comment]
![Capture](https://user-images.githubusercontent.com/52844170/103353210-dada5600-4ada-11eb-9daa-7390ce9c7e23.JPG)

T ko thấy file index của ô đâu nên ko rõ file đấy ô viết như nào, nhưng lỗi kia thì t nghĩ ô nên xem biến $product đã được khai báo chưa; đã gọi đến class ProductController chưa

**Comment by hungpy01199** [comment]
code ở /views/product/index.php chưa có lệnh echo nhưng t thêm echo vẫn lỗi tương tự.

**Comment by duynguyen9926** [comment]
T xử lí được r, mặc dù nó báo lỗi nhưng mà các dữ liệu vẫn lấy ra được, ví dụ như `$product->name` hay `$product->image` vẫn lôi ra được, với lại chạy trên web không bị lỗi nên t sẽ đóng issue ở đây.
