### ISSUE TITLE
Để tránh nhầm với những sản phẩm cho những lần đặt hàng về sau, ông nào biết làm sao để làm cho giỏ hàng trống sau khi đặt thành công không ?

### ISSUE THREAD

**Issue by duynguyen9926** [ThuanNguyen386/SE04-Nhom6.2#11]

**Comment by ThuanNguyen386** [comment]
Chỉnh cái controller khi click vào nút đặt hàng sao cho khi click vào đó thì tất cả các mặt hàng bị xóa khỏi giỏ hàng thôi

**Comment by toann99** [comment]
Viết thêm 1 cái function khi đặt hàng thành công thì tự động xóa sản phẩm đó trong giỏ hàng đi.

**Comment by dung111999** [comment]
Cái này t nghĩ phải chỉnh trong file frontend\controllers\CheckoutController.php, còn chỉnh thế nào thì t đang tìm hiểu

**Comment by hungpy01199** [comment]
sử dụng thêm 1 function nữa để check có ổn ko nhỉ

**Comment by ThuanNguyen386** [comment]
Thêm 1 function cũng ko sao
