### ISSUE TITLE
Có cách nào để tạo brand mới ko ae

### ISSUE THREAD

**Issue by ThuanNguyen386** [ThuanNguyen386/SE04-Nhom6.2#12]

**Comment by hungpy01199** [comment]
Thêm ở trong controller thôi mà nhỉ

**Comment by toann99** [comment]
Mình thêm ở trong controller là đc.

**Comment by duynguyen9926** [comment]
giao diện của admin ở bên backend/view có hỗ trợ thao tác với DB đó ông

**Comment by dung111999** [comment]
Thêm mới brand,product ô cứ vào backend/web/index.php?r=brand(r=product) nhấn create brand/create product là được nhé
