### ISSUE TITLE
Không hiển thị được ảnh phần frontend

### ISSUE THREAD

**Issue by ThuanNguyen386** [ThuanNguyen386/SE04-Nhom6.2#4]
<?php foreach($products as $items) : ?><img src="<?php echo $items->image ?><?php endforeach; ?>
T sử dụng đoạn code trên trong frontend/site/index.php để show ảnh sản phẩm nhưng không thành công. Ae có cách nào fix ko?

**Comment by ThuanNguyen386** [comment]
<?php foreach($products as $items) : ?><img src="<?php echo $items->image ?><?php endforeach; ?>
T sử dụng đoạn code trên trong frontend/site/index.php để show ảnh sản phẩm nhưng không thành công?Mọi người có cách fix ko?

**Comment by ThuanNguyen386** [comment]
<?php foreach($products as $items) : ?><img src="<?php echo $items->image ?><?php endforeach; ?>
T sử dụng đoạn code trên trong frontend/site/index.php để show ảnh sản phẩm nhưng không thành công?Mọi người có cách fix ko?

**Comment by ThuanNguyen386** [comment]
Tình hình là có đoạn code để hiển thị ảnh ở frontend nhưng mà không hiển thị được. Ae xem có cách nào chữa được lỗi này ko

**Comment by ThuanNguyen386** [comment]
<?php foreach($products as $items) : ?><img src="<?php echo $items->image ?><?php endforeach; ?>

**Comment by ThuanNguyen386** [comment]
đoạn code được lấy trong frontend/site/index.php để show ảnh sản phẩm

**Comment by ThuanNguyen386** [comment]
T vừa up file Code issue.txt ở branch main rồi đó nhưng mà nó ko hiển thị được ảnh sản phẩm bên frontend. Ae vào file đấy xem có cách nào sửa đc ko

**Comment by ThuanNguyen386** [comment]
`<?php foreach($products as $items) : ?><img src="<?php echo $items->image ?><?php endforeach; ?>`
Ae xem lỗi ở chỗ nào mà ko hiển thị được ảnh

**Comment by duynguyen9926** [comment]
Căn bản trình duyệt nó không thể truy cập được file mà không nằm trong webroot, nên mình sẽ vất cái thư mục **image**  vào trong **frontend/web**, vẫn sử dụng đoạn code bên trên là sẽ được

**Comment by toann99** [comment]
T đang thử bằng cách sử dụng var_dump($items->image) thì nó cũng ko hiện gì.

**Comment by duynguyen9926** [comment]
À t chỉnh lại code như này nhé
`<?php foreach($products as $items) : ?><img src="<?php echo $items->image ?>"><?php endforeach; ?>`

**Comment by hungpy01199** [comment]
> À t chỉnh lại code như này nhé
> `<?php foreach($products as $items) : ?><img src="<?php echo $items->image ?>"><?php endforeach; ?>`

Vẫn lỗi ông ạ

**Comment by hungpy01199** [comment]
github có tính năng insert code đấy ông

**Comment by dung111999** [comment]
T thử cách của Duy thì thấy được đấy, nhưng mà kiểu copy từ ảnh bên folder backend sang frontend hơi thủ công, t nghĩ tạm thời cứ thế đã để còn bổ sung chức năng khác, sau có gì mình bổ sung sau
