### ISSUE TITLE
Frontend không hiển thị hình ảnh sản phẩm???

### ISSUE THREAD

**Issue by ThuanNguyen386** [ThuanNguyen386/SE04-Nhom6.2#6]
Cái frontend chạy ở 1 số máy không hiển thị hình ảnh sản phẩm. Cái này fix như nào đây ae

**Comment by hungpy01199** [comment]
Kiểm tra xem ông clone đủ file chưa, file index trong views

**Comment by toann99** [comment]
Ông xem lại kết nối csdl, trình duyệt xem.

**Comment by duynguyen9926** [comment]
Tôi cũng bị lỗi này giống ông, vì nó không lấy được dữ liệu từ DB ra đấy, import lại DB mới đi ông, cấu trúc vẫn thế nhưng item thì Dũng đổi hết rồi nhưng có mỗi t với ông là chưa cập nhật

**Comment by ThuanNguyen386** [comment]
Hóa ra là phải vào phpmyadmin thì mới cập nhật được database
T fix được rồi

**Comment by dung111999** [comment]
Ai không hiển thị được thì xem lại db nhé

**Comment by ThuanNguyen386** [comment]
Ae nào ko hiển thị được hình ảnh thì vào phpmyadmin và cập nhật database mới nhất nha
